# Author: Daniel Benjamin Perez Morales
# GitHub: https://github.com/DanielPerezMoralesDev13
# Email: danielperezdev@proton.me

# Ejemplo de cómo cargar un archivo TOML
# Supongamos que tenemos un archivo llamado 'config.toml' con el siguiente contenido:
[settings]
theme = "dark"
version = 1.0